project_id = "fluxopay"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
port = 54322
major_version = 15

[studio]
enabled = true
port = 54323

[auth]
enabled = true
site_url = "http://192.168.1.202:3100"
additional_redirect_urls = [
  "http://192.168.1.202:3100/auth/callback",
  "http://127.0.0.1:3100/auth/callback"
]
jwt_expiry = 3600
enable_signup = true

[auth.email]
enable_signup = true
double_confirm_changes = true
enable_confirmations = false
